FROM python:3.8-slim

WORKDIR /usr/app

RUN apt-get update
RUN apt-get install ffmpeg -y


COPY ./src/requirements.txt .
RUN pip install -r requirements.txt

COPY ./src ./src

ENTRYPOINT python ./src/server.py