version: '3.1'

services:
  

  real-time-panorama:
    image: cloud.canister.io:5000/skyview/real-time-panorama
    restart: unless-stopped
    build:
      context: ./src
    ports:
      - "80:8080"



