version: '3.1'

services:
  

  RTP:
    build: .
    image: RTP
    command: yarn start
    expose:
      - 8080


  RTP-tests:
    image: RTP
    environment:
      APP_URL: http://RTP:8000
    depends_on:
      - RTP

networks:
  default:
    name: skyviewer
    driver: bridge