version: '3.1'

services:
  

  real-time-panorama:
    image: cloud.canister.io:5000/skyview/real-time-panorama
    build:
      context: ./src
    ports:
      - "8080:8080"


networks:
  default:
    name: skyviewer
    driver: bridge