# Default values for rt-panorama.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: "cloud.canister.io:5000"
  repository:  "cloud.canister.io:5000/skyview/real-time-panorama"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}


service:
  type: LoadBalancer
  port: 8081

nodeSelector: {}

tolerations: []

affinity: {}
