apiVersion: v1
kind: Service
metadata:
  name: {{ include "rt-panorama.fullname" . }}
  labels:
    {{- include "rt-panorama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "rt-panorama.selectorLabels" . | nindent 4 }}
